/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.table.DefaultTableModel;
import model.AlunoDAO;
import model.ClassAluno;

/**
 *
 * @author Bruno
 */
public class Aluno extends javax.swing.JFrame {

    /**
     * Creates new form Aluno
     */
    public Aluno() {
        initComponents();
        readTable();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Aluno");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtGrava = new javax.swing.JButton();
        TxtFieldNome = new javax.swing.JTextField();
        BtAltera = new javax.swing.JButton();
        BtExclui = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabAluno = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Nome");

        BtGrava.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/add.png"))); // NOI18N
        BtGrava.setText("Inserir");
        BtGrava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGravaActionPerformed(evt);
            }
        });

        BtAltera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/edit.png"))); // NOI18N
        BtAltera.setText("Alterar");
        BtAltera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlteraActionPerformed(evt);
            }
        });

        BtExclui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/delete.png"))); // NOI18N
        BtExclui.setText("Excluir");
        BtExclui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluiActionPerformed(evt);
            }
        });

        jTabAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabAlunoMouseClicked(evt);
            }
        });
        jTabAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTabAlunoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTabAluno);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/eraser.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtGrava, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                        .addGap(70, 70, 70)
                        .addComponent(BtAltera, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addGap(76, 76, 76)
                        .addComponent(BtExclui, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtFieldNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtGrava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtAltera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtExclui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtGravaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGravaActionPerformed
        // TODO add your handling code here:
        ClassAluno a = new ClassAluno();
        AlunoDAO dao = new AlunoDAO();
        a.setNome(TxtFieldNome.getText());
        dao.create(a);
        readTable();
        limpaCampos();
    }//GEN-LAST:event_BtGravaActionPerformed

    private void jTabAlunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabAlunoKeyReleased
        // TODO add your handling code here:
        carregaCampos();
    }//GEN-LAST:event_jTabAlunoKeyReleased

    private void jTabAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabAlunoMouseClicked
        // TODO add your handling code here:
        carregaCampos();
    }//GEN-LAST:event_jTabAlunoMouseClicked

    private void BtAlteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlteraActionPerformed
        // TODO add your handling code here:
        if (jTabAluno.getSelectedRow() != -1){
            
        ClassAluno a = new ClassAluno();
        AlunoDAO dao = new AlunoDAO();
        a.setNome(TxtFieldNome.getText());
        a.setCodigo((int) jTabAluno.getValueAt(jTabAluno.getSelectedRow(), 0));
        dao.update(a);
        readTable();
        limpaCampos();
        
        }
    }//GEN-LAST:event_BtAlteraActionPerformed

    private void BtExcluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluiActionPerformed
        // TODO add your handling code here:
     if (jTabAluno.getSelectedRow() != -1){
            
        ClassAluno a = new ClassAluno();
        AlunoDAO dao = new AlunoDAO();
        a.setCodigo((int) jTabAluno.getValueAt(jTabAluno.getSelectedRow(), 0));
        dao.delete(a);
        readTable();
        limpaCampos();
        
        }                
    }//GEN-LAST:event_BtExcluiActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        limpaCampos();
    }//GEN-LAST:event_jButton1ActionPerformed

        public void readTable(){
    
        DefaultTableModel modelo = (DefaultTableModel) jTabAluno.getModel();
        AlunoDAO adao = new AlunoDAO();
        modelo.setRowCount(0);
        
        for (ClassAluno a : adao.read()) {
            
             modelo.addRow(new Object[]{
                 a.getCodigo(),
                 a.getNome()
             }
             ); 
            
        }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aluno().setVisible(true);
            }
        });
    }
    
    private void limpaCampos(){
        TxtFieldNome.setText(null);
    }
    
    private void carregaCampos(){
        if (jTabAluno.getSelectedRow() != -1){
            
            TxtFieldNome.setText(jTabAluno.getValueAt(jTabAluno.getSelectedRow(), 1).toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAltera;
    private javax.swing.JButton BtExclui;
    private javax.swing.JButton BtGrava;
    private javax.swing.JTextField TxtFieldNome;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabAluno;
    // End of variables declaration//GEN-END:variables
}
