/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.table.DefaultTableModel;
import model.AlunoDAO;
import model.ClassAluno;
import model.ClassCurso;
import model.ClassMatricula;
import model.CursoDAO;
import model.MatriculaDAO;

/**
 *
 * @author Bruno
 */
public class Matricula extends javax.swing.JFrame {

    /**
     * Creates new form Matricula
     */
    public Matricula() {
        initComponents();
        readAluno(); 
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Matriculas");
    }
    
    public void readAluno(){
    
        DefaultTableModel modelo = (DefaultTableModel) jTabAluno.getModel();
        AlunoDAO adao = new AlunoDAO();
        modelo.setRowCount(0);
        
        for (ClassAluno a : adao.read()) {
            
                modelo.addRow(new Object[]{
                     a.getCodigo(),
                     a.getNome()
                }
            ); 
            
        }
    
    }
    
    public void readCurso(){
    
        if (jTabAluno.getSelectedRow() != -1){
            
            ClassAluno a = new ClassAluno();
            CursoDAO dao = new CursoDAO();
            a.setCodigo((int) jTabAluno.getValueAt(jTabAluno.getSelectedRow(), 0));

            DefaultTableModel modeloC = (DefaultTableModel) jTabCurso.getModel();
            modeloC.setRowCount(0);

            for (ClassCurso c : dao.readDisp(a)) {

                 modeloC.addRow(new Object[]{
                     c.getCodigo(),
                     c.getDescricao(),
                     c.getEmenta()
                 }
                 ); 

            }
        
        }  
    
    }
    
    public void readMat(){
    
         if (jTabAluno.getSelectedRow() != -1){
            
            ClassAluno a = new ClassAluno();
            MatriculaDAO dao = new MatriculaDAO();
            a.setCodigo((int) jTabAluno.getValueAt(jTabAluno.getSelectedRow(), 0));

            DefaultTableModel modeloM = (DefaultTableModel) jTabMat.getModel();
            modeloM.setRowCount(0);

            for (ClassMatricula m : dao.read(a)) {

                 modeloM.addRow(new Object[]{
                     
                     m.getCodigo(),
                     m.getCodigo_curso(),
                     m.getDescricao(),
                     m.getEmenta()
                 }
                 ); 

            }
        
        }  
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabAluno = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabCurso = new javax.swing.JTable();
        BtIncCurso = new javax.swing.JButton();
        BtDelCurso = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTabMat = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabAlunoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabAluno);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Alunos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Cursos Disponíveis");

        jTabCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DESCRICAO", "EMENTA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTabCurso);

        BtIncCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/right-arrow.png"))); // NOI18N
        BtIncCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIncCursoActionPerformed(evt);
            }
        });

        BtDelCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/left-arrow.png"))); // NOI18N
        BtDelCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDelCursoActionPerformed(evt);
            }
        });

        jTabMat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "COD_CURSO", "DESCRICAO", "EMENTA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTabMat);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Cursos Matriculados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtDelCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(BtIncCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(133, 133, 133))
            .addGroup(layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(BtIncCurso)
                        .addGap(100, 100, 100)
                        .addComponent(BtDelCurso)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabAlunoMouseClicked
        // TODO add your handling code here:
        readCurso();
        readMat();
    }//GEN-LAST:event_jTabAlunoMouseClicked

    private void BtIncCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIncCursoActionPerformed
        // TODO add your handling code here:
        if ((jTabAluno.getSelectedRow() != -1) && (jTabCurso.getSelectedRow() != -1)){
            
            ClassAluno a = new ClassAluno();
            ClassCurso c = new ClassCurso();
            MatriculaDAO dao = new MatriculaDAO();
            a.setCodigo((int) jTabAluno.getValueAt(jTabAluno.getSelectedRow(), 0));
            c.setCodigo((int) jTabCurso.getValueAt(jTabCurso.getSelectedRow(), 0));

            dao.create(c, a);
            readMat();
            readCurso();
        }          
    }//GEN-LAST:event_BtIncCursoActionPerformed

    private void BtDelCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDelCursoActionPerformed
        // TODO add your handling code here:
        if (jTabMat.getSelectedRow() != -1){
            
            ClassMatricula m = new ClassMatricula();
            MatriculaDAO dao = new MatriculaDAO();
            m.setCodigo((int) jTabMat.getValueAt(jTabMat.getSelectedRow(), 0));
            dao.delete(m);
            readMat();
            readCurso();
        }       
    }//GEN-LAST:event_BtDelCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matricula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtDelCurso;
    private javax.swing.JButton BtIncCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTabAluno;
    private javax.swing.JTable jTabCurso;
    private javax.swing.JTable jTabMat;
    // End of variables declaration//GEN-END:variables
}
