-- MySQL Script generated by MySQL Workbench
-- Thu Mar  7 23:59:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbvr
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbvr
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbvr` DEFAULT CHARACTER SET latin1 ;
USE `dbvr` ;

-- -----------------------------------------------------
-- Table `dbvr`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbvr`.`aluno` (
  `CODIGO` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`CODIGO`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbvr`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbvr`.`curso` (
  `CODIGO` INT(11) NOT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(50) NULL DEFAULT NULL,
  `EMENTA` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`CODIGO`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbvr`.`curso_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbvr`.`curso_aluno` (
  `CODIGO` INT(10) NOT NULL AUTO_INCREMENT,
  `CODIGO_ALUNO` INT(11) NULL DEFAULT NULL,
  `CODIGO_CURSO` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`CODIGO`),
  CONSTRAINT `FK_ALUNO`
    FOREIGN KEY (`CODIGO_ALUNO`)
    REFERENCES `dbvr`.`aluno` (`CODIGO`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_CURSO`
    FOREIGN KEY (`CODIGO_CURSO`)
    REFERENCES `dbvr`.`curso` (`CODIGO`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
